### ISSUE TITLE
4 Sum problem (Leetcode) Time:91ms, Space:13.3

### ISSUE THREAD

**Issue by Akshay1810** [sachin10101998/leetcode-solutions#7]
I want to contribute this problem under hactoberfest tag.

**Comment by sachin10101998** [comment]
Bro, issues are not counted for hacktoberfest. Only pull requests count.

**Comment by Akshay1810** [comment]
I want to ask first before contributing so I raised this issue.

**Comment by dhruvgarg02** [comment]
Hi, @sachin10101998 I want to work on the problem! can I raise a PR for this? Or can I raise a PR for any other leetcode question??

**Comment by sachin10101998** [comment]
Bhej de bhai.
